version: "3"
vars:
  SERVICE_NAME: orchestrator
  NAMESPACE: flags-gg
tasks:
  # Utility Commands
  setup:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - go install golang.org/x/tools/cmd/goimports
      - go install google.golang.org/protobuf/cmd/protoc-gen-go
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
  make-temp-files:
    cmds:
      - task: get-latest-tag
      - task: get-commit-hash
  get-latest-tag:
    cmds:
      - |
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [[ -z "$latest_tag" ]]; then
          echo "0.0.1" > .latest_tag
        else
          echo $latest_tag | awk -F. '{printf "%d.%d.%d", $1, $2, $3}' > .latest_tag
        fi
    silent: true
  get-commit-hash:
    cmd: git rev-parse --short HEAD > .commit_hash
    silent: true
  clean-git-file:
    cmds:
      - rm .latest_tag
      - rm .commit_hash
  fmt:
    cmds:
      - goimports -w .
      - gofmt -w .
      - go clean ./...
      - go mod tidy
  test:
    cmd: go test -v -race -bench=./... -benchmem -timeout=120s -cover -coverprofile=coverage.txt -covermode=atomic ./...

  clean:
    cmds:
      - go clean -cache -testcache -modcache
      - rm -rf ./bin
      - rm -rf ./dist
      - rm -rf ./coverage.txt

  # Publish Commands
  publish-images:
    cmds:
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} --all-platforms
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --all-platforms
    vars:
      COMMIT_HASH:
        sh: cat .commit_hash
  publish-hash:
    cmds:
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} --all-platforms
    vars:
      COMMIT_HASH:
        sh: cat .commit_hash

  # Build Commands
  build-images:
    cmds:
      - task: get-latest-tag
        vars:
          LATEST_TAG:
            sh: cat .latest_tag
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - nerdctl build --platform=amd64,arm64 --tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} --build-arg VERSION={{.LATEST_TAG}} --build-arg BUILD={{.COMMIT_HASH}} --build-arg SERVICE_NAME={{.SERVICE_NAME}} -f ./k8s/Containerfile .
      - nerdctl tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
      COMMIT_HASH:
        sh: cat .commit_hash
  build-hash:
    cmds:
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - nerdctl build --platform=amd64,arm64 --tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} --build-arg VERSION={{.LATEST_TAG}} --build-arg BUILD={{.COMMIT_HASH}} --build-arg SERVICE_NAME={{.SERVICE_NAME}} -f ./k8s/Containerfile .
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
      COMMIT_HASH:
        sh: cat .commit_hash
  build-push-latest:
    cmds:
      - task: get-latest-tag
      - task: get-commit-hash
      - nerdctl build --platform=amd64,arm64 --tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --build-arg VERSION={{.LATEST_TAG}} --build-arg BUILD={{.COMMIT_HASH}} --build-arg SERVICE_NAME={{.SERVICE_NAME}} -f ./k8s/Containerfile .
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --all-platforms
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
      COMMIT_HASH:
        sh: cat .commit_hash
  build:
    cmds:
      - task: build-images

  # Deploy Commands
  deploy:
    cmd: kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} -n {{.NAMESPACE}}
    vars:
      COMMIT_HASH:
        sh: cat .commit_hash
  deploy-latest:
    cmds:
      - kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/{{.SERVICE_NAME}} -n {{.NAMESPACE}}
  deploy-latest-tag:
    cmds:
      - kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.LATEST_TAG}} -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/{{.SERVICE_NAME}} -n {{.NAMESPACE}}
    vars:
      LATEST_TAG:
        sh: cat .latest_tag

  # Extras
  build-deploy:
    cmds:
      - task: build-images
      - task: publish-images
      - task: deploy
  build-deploy-latest:
    cmds:
      - task: build-push-latest
      - task: deploy-latest
  build-deploy-hash:
    cmds:
      - task: get-commit-hash
      - task: build-hash
      - task: publish-hash
      - task: deploy

  go-secure:
    cmds:
      - go vet ./...
      - golangci-lint run ./...
      - staticcheck ./...
      - govulncheck ./...
      - gosec ./...
