---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: flags-gg
  labels:
    name: orchestrator
    app: orchestrator
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: orchestrator
      name: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        name: orchestrator
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "flags-gg-vault-orchestrator-sidecar"
        vault.hashicorp.com/secret-volume-path: "/secrets"
        vault.hashicorp.com/agent-inject-secret-orchestrator: "kv/data/flags-gg/orchestrator"
        vault.hashicorp.com/agent-inject-template-orchestrator.json: |
          {{ with secret "kv/data/flags-gg/orchestrator" }}
          {{ .Data.data | toJSON }}
          {{ end }}
    spec:
      serviceAccountName: "vault-orchestrator-sidecar"
      hostAliases:
        - ip: "192.168.1.67"
          hostnames:
            - "db.chewed-k8s.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: orchestrator
          image: containers.chewed-k8s.net/flags-gg/orchestrator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3000
              name: grpc
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_HOST
              value: "https://vault.chewed-k8s.net"
            - name: LOCAL_VAULT_PATH
              value: "/secrets/orchestrator.json"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: vault-token

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: flags-gg
  labels:
    app: orchestrator
    name: orchestrator
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: grpc
  selector:
    app: orchestrator
    name: orchestrator

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flags-gg
  name: orchestrator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: live-issuer
  labels:
    app: orchestrator
    name: orchestrator
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.flags.gg
      secretName: orchestrator-flags-gg-tls
  rules:
    - host: api.flags.gg
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 80
